#what to back up (use absolute paths or ~ expansion handled by shell)
  source_directories:
    - /volume1
  repositories:
    - path: /root/borgrepo

  encryption_passphrase: blabla

  keep_daily: 7
